### ISSUE TITLE
fix: many API requests from Routes Controller

### ISSUE THREAD

**Issue by apricote** [hetznercloud/hcloud-cloud-controller-manager#395]
We are sending a request every ten seconds to Hetzner Cloud API if the routing functionality is active (default when Networking is activated). This equals 1/10th of the default API rate limit on new accounts.

![Example metrics that demonstrate the issue described here](https://user-images.githubusercontent.com/3393079/225241350-264ab8a7-b95b-4134-86d4-9ce548aab303.png)

This happens even though nothing has changed on the Kubernetes side, and there is no real need to reconcile this often. It should be enough to reconcile this on Node IP changes and when Nodes are added or removed.

This behaviour is coming from [`k/cloud-provider`](https://github.com/kubernetes/cloud-provider/blob/0dac8cc4d471bfbfdf48e7d6a9c039efb8d21d88/controllers/route/route_controller.go#L113-L122) and there exists an upstream issue for it: kubernetes/kubernetes#60646

**Comment by samcday** [comment]
The main issue here is the fact that [route reconciliation isn't triggered properly](https://github.com/kubernetes/cloud-provider/blob/0dac8cc4d471bfbfdf48e7d6a9c039efb8d21d88/controllers/route/route_controller.go#L113-L117).

If the reconciliation logic was more internally coherent, we could safely increase the default 10s re-reconciliation interval to something like 1m. This would mean that new servers should get routes quickly, but routes that were modified out of band might take a minute or two to self-heal.

Longer term we've been discussing the possibility/merits of implementing hccm's logic in a standard kubebuilder project. In that case we would have full control over things like this and be able to much more easily tune this without resorting to forking the upstream or pinging a 5 year old ticket.

In the interim, I propose configuring the [reconciliation period](https://github.com/kubernetes/cloud-provider/blob/0dac8cc4d471bfbfdf48e7d6a9c039efb8d21d88/config/v1alpha1/defaults.go#L69) from 10s -> 30s. This means that new servers take a little longer to get set up, but the normal case is 3x less API traffic.

**Comment by apricote** [comment]
> In the interim, I propose configuring the [reconciliation period](https://github.com/kubernetes/cloud-provider/blob/0dac8cc4d471bfbfdf48e7d6a9c039efb8d21d88/config/v1alpha1/defaults.go#L69) from 10s -> 30s. This means that new servers take a little longer to get set up, but the normal case is 3x less API traffic.

Implemented in #403.

**Comment by jooola** [comment]
We recently fixed a bug related to the network API calls https://github.com/hetznercloud/hcloud-cloud-controller-manager/commit/546103879336e86ade1f2217f33003aa125bdb98

Is there a chance that this issue is related to the bug we fixed above ? Do we have some metrics that proves that this isn't an issue anymore ?

**Comment by apricote** [comment]
Unfortunately this is not fixed yet. Reconciliation still happens on a 30s interval (or whatever people configure). This can only be properly fixed by upstream `k/cloud-provider`: https://github.com/kubernetes/kubernetes/issues/60646

**Comment by lukasmetzner** [comment]
The issue is addressed upstream in Kubernetes. To fix this we need to create a Kubernetes Enhancement Proposal (KEP). The progress is tracked in https://github.com/kubernetes/enhancements/issues/5237. 

The current implementation MVP can be found here: https://github.com/kubernetes/kubernetes/pull/131220
